// Auto-generated content constants - DO NOT EDIT MANUALLY
// Last updated: 2025-08-05T11:26:48.651Z
// Generated by: scripts/sync-content-across-platforms.js

export const APP_CONSTANTS = {
  API_BASE_URL: 'https://dahabiyatnilecruise.com', // Production domain
  
  DEVELOPER: {
    NAME: 'Just X Development',
    COMPANY: 'Just X',
    PHONE: '+20 1200958713',
    EMAIL: 'just-x1@outlook.com',
    WEBSITE: 'https://justx.com',
    BRANDING_TEXT: 'crafted with love in the land of the Pharaohs by Just X',
    LOGO: '/images/94cb4d03-c000-4b5a-9f74-94a6ff0b1668.webp'
  },
  
  COMPANY: {
    NAME: 'Cleopatra Dahabiyat',
    ADDRESS: 'Luxor, Egypt',
    PHONE: '+20 123 456 789',
    EMAIL: 'info@cleopatradarabiyat.com'
  },
  
  ITINERARIES: {
    HERO_TITLE: 'Discover Egypt',
    HERO_SUBTITLE: 'Discover Ancient Egypt Through Carefully Crafted Journeys',
    EMPTY_STATE_TITLE: 'There are no itineraries yet',
    EMPTY_STATE_DESCRIPTION: 'Our pharaonic scholars are crafting extraordinary journeys'
  }
};

export default APP_CONSTANTS;
